### ISSUE TITLE
Delete field db entry before inserting it (frontend)

### ISSUE THREAD

**Issue by nathanhornby** [nathanhornby/hashid_field#18]
Not sure if this is actually required, but it fixed a problem on a site I'm working on and seems consistent with how other fields populate the db (`DELETE` then `INSERT`), I assume to avoid potential duplication issues, although that seems crude?

**Comment by nitriques** [comment]
> although that seems crude?

Yes it is but that's how things works right now...

It to account field can could have multiple rows per entries: finding out the diff is hard in certain cases.
