### ISSUE TITLE
The `value` column should have a unique key

### ISSUE THREAD

**Issue by nitriques** [nathanhornby/hashid_field#21]
Not just a key, but a real unique key. I really do think that a hash should be unique.

Also, please consider implementing [this method](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.field.php#L238) and making it return true.

Thanks!

(I could also send a PR if you are interested)

**Comment by nathanhornby** [comment]
Closing for now, feel free to re-open if necessary!

**Comment by nitriques** [comment]
No problems.

**Comment by nitriques** [comment]
I am re-opening this as I need to do it ASAP :)

**Comment by nathanhornby** [comment]
Checking the uniqueness of the ID?

The main issue IMO remains that the seed is the entry ID. So if we *do* hit a collision, what do we do about it?

**Comment by nitriques** [comment]
>  what do we do about it?

Throw an error ! I really need a way to prevent duplicate hashes

**Comment by nathanhornby** [comment]
Sure, but then what? You can't change the hash, or the entry id. And so re-attempting a save will just give you the same error again. What can a user do about it?

I don't have any issue in principle with detecting collisions though (ordinarily it would be a given), if you've thought about a way to handle it though I'm all ears! :)

(How are you getting duplicates, out if interest?)

**Comment by nitriques** [comment]
> What can a user do about it?

Delete the newly created entry and start again, sadly. With a new entry_id it should not collide.

> How are you getting duplicates, out if interest

Currently I am not... But I have section with hash id of 3 or 4 in length so it can be possible to exhaust them all...  So maybe we could increment the length when a collision is found ?

**Comment by nathanhornby** [comment]
I'll have to have a check, as I can't remember how it was set up - but at least in version 2 of Hashid you can only set a *minimum* length (at least in the elixir version I used just yesterday!) - otherwise that sounds like an interesting approach.

I guess that's fine really, from what I understand it should essentially never happen, so for an edge case it's ok if it's a bit clunky - as long as there's a way to move past it!

**Comment by nitriques** [comment]
>  as long as there's a way to move past it!

Yeah that's the hard part. But insuring data integrity is more important that UX on that point IMHO.

**Comment by nathanhornby** [comment]
Fair point.

**Comment by nitriques** [comment]
Fixed in 2.0.0 :)
