### ISSUE TITLE
How to return hashid in xml when the entry created successfully?

### ISSUE THREAD

**Issue by kamwing** [nathanhornby/hashid_field#25]
By default. Symphony event return the entry id in xml. And i want to get the hashid when the entry created via frontend event.

**Comment by nathanhornby** [comment]
Hi @kamwing 

Sorry I haven't replied before, I only just noticed the issue!

I'm not sure I know how to do this unfortunately.

You could perhaps do some kind of datasource chain, that gets the recently created entry by its ID and expose the Hash to the front-end param pool that way? Similar to how Email Template Manager works.

If you haven't done already I'd ask about this on the forum, as someone else will likely be able to assist you better than me!

**Comment by nitriques** [comment]
> How to return hashid in xml when the entry created successfully? 

Create a custom event or use a data source that reads the id from the event.
