### ISSUE TITLE
Implementation logic improvement

### ISSUE THREAD

**Issue by michael-e** [nathanhornby/hashid_field#28]
I don't really get the point of the current implementation of `processRawFieldData` and `compile`.

1. `processRawFieldData` will actually save data (if not empty).
2. `compile`will only compile (and insert to the DB) if there is no data.

This means that you could POST a hash which wouldn't get overridden by the compile function.

I would expect the compile function to always do the work. To achieve this, `processRawFieldData` could return an array with a `null` value, and the compile function could do a `Symphony::Database()->update` instead of a `Symphony::Database()->insert`. (This is the way the Reflection Field does it.)

If you want this to be changed, I could send a pull request. But maybe the above is intended?

**Comment by nathanhornby** [comment]
Hi @michael-e 

There's a very good chance (99%) that was copied and pasted from another extension, so I'd be happy to accept a pull request from you, as it's almost definitely not intended. Unfortunately I wrote it so long ago and haven't touched any Symphony extension dev in a while, that I have no idea of my intentions at the time!

**Comment by michael-e** [comment]
OK, I will try! But it may take some days. Too many Mondays here…

**Comment by nathanhornby** [comment]
No rush at all - I'm just happy for any contribution :)
