### ISSUE TITLE
Hashid not updated when entry is edited from the frontend

### ISSUE THREAD

**Issue by michael-e** [nathanhornby/hashid_field#31]
At the moment, the Hashid is saved/updated:

* when an entry is *created* or *edited* in the backend
* when an entry is *created* from the frontend

It is not updated, however, when the entry is *edited* from the frontend. 

This is a conceptual flaw which can also be seen in the reflection field (and probably is has been taken from there). The idea of "registering" a field in the `checkPostFieldData` function doesn't work as expected, because Symphony won't call this function for fields that are not included in the POST data.

I will try and fix this together with #28 (if @nitriques gives his OK, see my question in https://github.com/nathanhornby/hashid_field/commit/c4ad03ac077646b788a3ea3c0cf3b8b8d25c5100#commitcomment-15529561).

**Comment by nathanhornby** [comment]
:+1:

**Comment by nitriques** [comment]
> The idea of "registering" a field in the checkPostFieldData function doesn't work as expected, because Symphony won't call this function for fields that are not included in the POST data.

Your commits LGTM :)
