### ISSUE TITLE
Upgrade to Hashids 1.0.x

### ISSUE THREAD

**Issue by michael-e** [nathanhornby/hashid_field#32]
It might be nice to update the Hashids library to version 1.0.x. It seems to be a well-maintained project.

Should we [use Composer to do it](https://github.com/ivanakimov/hashids.php#installation)?

If you like the idea, I could send a PR.

**Comment by nathanhornby** [comment]
I was thinking this just a couple of days ago actually. You know the PHP ecosystem better than I do @michael-e , if you think that's the best approach then I'm happy with it. Any opinions @nitriques ?

**Comment by nitriques** [comment]
@michael-e Yes please! I've used composer [here](https://github.com/DeuxHuitHuit/google_analytics_dashboard) but you have to commit the dependancies... 

Spoiler alert: I'm thinking about adding the possibility to install extension via composer too ;)

**Comment by nitriques** [comment]
This has been done in 2.0.0!

**Comment by michael-e** [comment]
No issues left. :-)

**Comment by nitriques** [comment]
Yup! Thanks again Michael!

**Comment by nathanhornby** [comment]
:tada:
