### ISSUE TITLE
Hash is displayed in entries table even if it has never been saved

### ISSUE THREAD

**Issue by michael-e** [nathanhornby/hashid_field#35]
As the title says, it is misleading for developers and authors alike to display hashes in the entries table even if these hashes have never been saved.

I will address this issue by adding a fix to my open pull request https://github.com/nathanhornby/hashid_field/pull/34.

**Comment by nitriques** [comment]
Micheal, how can the entry be in the entries table (publish index) if it's not yet created ?

**Comment by michael-e** [comment]
See my above commit. `prepareTextValue` __creates__ a hash instead of reading it from the database. That's why I completely removed that function in my commit.

**Comment by nitriques** [comment]
Ah! good point thanks.
