### ISSUE TITLE
Symphony fatal error when saving field settings

### ISSUE THREAD

**Issue by johnpuddephatt** [nathanhornby/hashid_field#37]
On 2.6.7, when adding a hashid field to a section, or changing the settings of an existing hashid field, upon hitting 'Save changes', I get the following error:

````
Symphony Fatal Database Error:
Field 'size' doesn't have a default value

An error occurred while attempting to execute the following query
INSERT INTO `sym_fields_hashid_field` (`field_id`, `length`, `salt`) VALUES ('78', '5', 'Symphony')
````

Despite this, the field works as expected in both the backend and frontend.

**Comment by johnpuddephatt** [comment]
Adding a default value for the 'size' field in the SQL table fixes this.

**Comment by nitriques** [comment]
Thanks for reporting. Which version of the hash field are you running ?

**Comment by johnpuddephatt** [comment]
Sorry should have said – the latest, so 2.0.0

**Comment by nitriques** [comment]
Perfect, thanks, just wanted to make sure ;)

**Comment by nitriques** [comment]
@johnpuddephatt, @ChoboHub fixed the issue and it's in the `integration` branch. Would you mind testing it and confirm that the issue is gone ? Thanks!

**Comment by johnpuddephatt** [comment]
LGTM!

**Comment by nitriques** [comment]
Released !
