### ISSUE TITLE
Duplicate entry 'wDgK7x9W0yJ5joARRqmVlvQoRB48kb' for key 'value'

### ISSUE THREAD

**Issue by wdebusschere** [nathanhornby/hashid_field#40]
private $_alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';  

Table = COLLATE=utf8_unicode_ci . 

hash entryid 32443 string(30) "wDgK7x9W0yJ5joA**R**RqmVlvQoRB48kb" 
hash entryid 75645 string(30) "wDgK7x9W0yJ5joA**r**RqmVlvQoRB48kb"

**Comment by wdebusschere** [comment]
fix? 
private $_alphabet = 'abcdefghijklmnopqrstuvwxyz1234567890';// ABCDEFGHIJKLMNOPQRSTUVWXYZ

**Comment by nitriques** [comment]
Do you have the stack trace ?

**Comment by wdebusschere** [comment]
`		Symphony Fatal Database Error: Duplicate entry '985wKMzJADy1GxvoYZ4Va70PvBngmd' for key 'value' An error occurred while attempting to execute the following query
		INSERT INTO `sym_entries_data_312` (`entry_id`, `value`) VALUES ('37797', '985wKMzJADy1GxvoYZ4Va70PvBngmd')
		Backtrace
		[/Users/xxx/Sites/client/symphony/lib/toolkit/class.mysql.php:554]
		    MySQL->__error();
		[/Users/xxx/Sites/client/symphony/lib/toolkit/class.mysql.php:690]
		    MySQL->query();
		[/Users/xxx/Sites/client/symphony/lib/toolkit/class.entrymanager.php:164]
		    MySQL->insert();
		[/Users/xxx/Sites/client/symphony/lib/toolkit/class.entrymanager.php:235]
		    EntryManager::saveFieldData();
		[/Users/xxx/Sites/client/symphony/lib/toolkit/class.entry.php:357]
		    EntryManager::edit();
		[/Users/xxx/Sites/client/workspace/events/event.import.php:458]
		    Entry->commit();
		[/Users/xxx/Sites/client/workspace/events/event.import.php:118]
		    eventimport->insertProject();
		[/Users/xxx/Sites/client/workspace/events/event.import.php:60]
		    eventimport->execute();
		[/Users/xxx/Sites/client/symphony/lib/toolkit/class.frontendpage.php:756]
		    eventimport->load();
		[/Users/xxx/Sites/client/symphony/lib/toolkit/class.frontendpage.php:455]
		    FrontendPage->processEvents();
		[/Users/xxx/Sites/client/symphony/lib/toolkit/class.frontendpage.php:193]
		    FrontendPage->__buildPage();
		[/Users/xxx/Sites/client/symphony/lib/core/class.frontend.php:106]
		    FrontendPage->generate();
		[/Users/xxx/Sites/client/symphony/lib/boot/func.utilities.php:253]
		    Frontend->display();
		[/Users/xxx/Sites/client/symphony/lib/boot/func.utilities.php:235]
		    symphony_launcher();
		[/Users/xxx/Sites/client/index.php:19]
		    symphony();
		 
		Database Query Log
		[0.0001] SET character_set_connection = 'utf8', character_set_database = 'utf8', character_set_server = 'utf8';
		[0.0001] SET CHARACTER SET 'utf8';
		[0.0001] SET time_zone = '+01:00';
		 
`

**Comment by nitriques** [comment]
Oh! That sucks. And you confirm that both hashes are the same when lowercase'd ?

**Comment by nitriques** [comment]
Ah ok I just saw the R ;)

**Comment by wdebusschere** [comment]
YES

FYI: my case: 1809 records, 38 duplicates if i search for duplicates ignoring case..

**Comment by nitriques** [comment]
I think this is the proper fix. We need case sensitivity here.

**Comment by jurajkapsz** [comment]
I guess I also ran into this - created hash entries were dropped from DB and thus lost.

After changing the DB's `value` column to `utf8_bin` collation it looks like everything works.

Maybe I can try to create a commit fix for this?

**Comment by jurajkapsz** [comment]
Speaking of:

> Maybe I can try to create a commit fix for this?

There is a update pull request pending (#39), so maybe it will be tricky?

**Comment by jurajkapsz** [comment]
In any case, thanks very much for this `utf_bin` find!

**Comment by nitriques** [comment]
@jurajkapsz No please go ahead an create a PR with the fix, we will rebase #39. Thanks !

**Comment by jurajkapsz** [comment]
@nitriques ok, almost finished.

**One Question**: Does it make sense to also change the collation to `utf8_bin` of `tbl_fields_hashid_field` table [salt column](https://github.com/nathanhornby/hashid_field/blob/master/extension.driver.php#L69-L76)?
